version: '3.7'

services:

  pedidos:
    build:
      context: ./services/pedidos
      dockerfile: Dockerfile-prod
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@pedidos-db:5432/pedidos_dev  # nuevo
      - DATABASE_TEST_URL=postgres://postgres:postgres@pedidos-db:5432/pedidos_test  # nuevo
    depends_on:
      - pedidos-db

  pedidos-db:
    build:
      context: ./services/pedidos/project/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - pedidos