version: '3.7'

services:

  pedidos:
    build:
      context: ./services/pedidos
      dockerfile: Dockerfile-dev
    volumes:
      - './services/pedidos:/usr/src/app'
    ports:
      - 5002:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@pedidos-db:5432/pedidos_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@pedidos-db:5432/pedidos_test
    depends_on:
      - pedidos-db

  pedidos-db:
    build:
      context: ./services/pedidos/project/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres



